# -*- coding: utf-8 -*-
"""Week_02_F3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S9o21FKyWsgzX8_Mf41PRRjtbZ0ptxH5
"""

print("hello world")

# int age =10
age=10
name="Ali"
cgpa=3.2
login=True

print(age)
print(name)
print(cgpa)
print(login)

#Data Types Check
print(type(age))
print(type(name))
print(type(cgpa))
print(type(login))

value = input("Enter Your age :")
# print(value+10)
print(type(value))

res = int(value)
print(res+10)
print(type(res))

sem =5
credit_hours=90
if sem!=6 or credit_hours>50:
  print("Eligible for FYP")
elif credit_hours>=90:
  print("Eligible for FYP but with extra summer courses")
else:
  print("Error")

# Debugggg
# sem =5
# credit_hours=90
# if sem!=6 ||  credit_hours>50:
#   print("Eligible for FYP")
# elif credit_hours>=90:
#   print("Eligible for FYP but with extra summer courses")
# else:
#   print("Error")

age =10
std_name = "Ahmad"
print(f"Your name is {std_name} and age is {age}")

array = [1,2,3,4,5,"Ali", 3.5,3,4,"UCP LAHORE", True]
print(array)

# print(type(array))
# print(dir(array))
# print(help(array))

#Insertion
array.append("New item")
print(array)
array.insert(0,"Fruits")
print(array)

array.extend([1,2,3,4])
print(array)
#Insertion
array.pop(3)
print(array)
array.remove("Ali")
print(array)

print(array)
print(array.count(1))

res =array.copy()
print(res)
# array.clear()
print(array)

my_info = "Hi, hello how are you..I'm in UCP for AI-LAb session"

#String indexing + String Built-in methods
print(my_info[2:15])
print(my_info[2:])
print(my_info[:])
print(my_info[:18])
print(my_info[2:255:4])
print(my_info[::-1]) #important
print(dir(str))

# for (int i=0;i>100;i++){
#     cout
# }

# for i in range(10):
#   print(i, end=" ")

# for i in range(2,10):
#   print(i, end=" ")


for i in range(40,0,-3):
  print(i, end=" ")

for i in array:
  print(i, end="")

i=10

while i<0:
  print(i)
  i=i-1

def Sum(a,b):
  return a+b

print(Sum(2,4))

#filing

with open('data.txt','w') as name:
  name.write("hello, UCP")

with open('data.txt','r') as name:
  data = name.read()
  print(data)

set1 = {1,2,3,4,5,6,2,3,4}
set2= {3,4,5,6,2,3,4,7}
set2.add(50)
print(set2)

print(set1.intersection(set2))

mytuple =(1,3,4,7,6,4,5,6)
print(mytuple)
mytuple.index(4)

dic = {
    "name":"Ali",
    "Age" : 20,
    "login" : True
}

# print(dic)

for i in  dic.values():
  print(i)

class Person:
  Univeristy = "UCP"
  def __init__(self, name ,age , address):
    self.My_name = name
    self.my_age = age
    self.my_add= address
    self.cgpa = 3.0

  def display(self):
    print(f"My name is {self.My_name} and age is {self.my_age}")
    print(f"My Uni is {self.Univeristy}")
    print(f"My cgpa is {self.cgpa}")


obj1 = Person("ali",10,"Karachi")
obj1.display()
